//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaApp.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SocialMediaAppEntities : DbContext
    {
        public SocialMediaAppEntities()
            : base("name=SocialMediaAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommentLike> CommentLikes { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<PasswordChangeHistory> PasswordChangeHistories { get; set; }
        public virtual DbSet<PostComment> PostComments { get; set; }
        public virtual DbSet<PostLike> PostLikes { get; set; }
        public virtual DbSet<UserData> UserDatas { get; set; }
        public virtual DbSet<UserFriend> UserFriends { get; set; }
        public virtual DbSet<UserMessage> UserMessages { get; set; }
        public virtual DbSet<UserPost> UserPosts { get; set; }
        public virtual DbSet<UserStory> UserStories { get; set; }
        public virtual DbSet<UserStoryLike> UserStoryLikes { get; set; }
        public virtual DbSet<PasswordResetToken> PasswordResetTokens { get; set; }
        public virtual DbSet<StoryView> StoryViews { get; set; }
    
        public virtual ObjectResult<GetAllStory_Result> GetAllStory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllStory_Result>("GetAllStory");
        }
    
        public virtual ObjectResult<GetLastComment_Result> GetLastComment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLastComment_Result>("GetLastComment");
        }
    
        public virtual ObjectResult<GetLastPost_Result> GetLastPost()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLastPost_Result>("GetLastPost");
        }
    
        public virtual ObjectResult<GetNotifications_Result> GetNotifications()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNotifications_Result>("GetNotifications");
        }
    
        public virtual ObjectResult<GetUserById_Result> GetUserById(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserById_Result>("GetUserById", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<GetUserNotifications_Result> GetUserNotifications()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserNotifications_Result>("GetUserNotifications");
        }
    
        public virtual ObjectResult<GetAllNotifications_Result> GetAllNotifications()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllNotifications_Result>("GetAllNotifications");
        }
    
        public virtual int AddUser(string email, string userPassword, string profilePhoto)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var userPasswordParameter = userPassword != null ?
                new ObjectParameter("UserPassword", userPassword) :
                new ObjectParameter("UserPassword", typeof(string));
    
            var profilePhotoParameter = profilePhoto != null ?
                new ObjectParameter("ProfilePhoto", profilePhoto) :
                new ObjectParameter("ProfilePhoto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddUser", emailParameter, userPasswordParameter, profilePhotoParameter);
        }
    
        public virtual ObjectResult<GetUser_Result> GetUser(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUser_Result>("GetUser", idParameter);
        }
    
        public virtual int UpdateUserInfo(Nullable<int> id, string firstName, string lastName, string city, string userPassword, string email, string gender, string interests, string phoneNumber, string bio, Nullable<System.DateTime> birthDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var userPasswordParameter = userPassword != null ?
                new ObjectParameter("UserPassword", userPassword) :
                new ObjectParameter("UserPassword", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var interestsParameter = interests != null ?
                new ObjectParameter("Interests", interests) :
                new ObjectParameter("Interests", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var bioParameter = bio != null ?
                new ObjectParameter("Bio", bio) :
                new ObjectParameter("Bio", typeof(string));
    
            var birthDateParameter = birthDate.HasValue ?
                new ObjectParameter("BirthDate", birthDate) :
                new ObjectParameter("BirthDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUserInfo", idParameter, firstNameParameter, lastNameParameter, cityParameter, userPasswordParameter, emailParameter, genderParameter, interestsParameter, phoneNumberParameter, bioParameter, birthDateParameter);
        }
    
        public virtual int UpdateStoryView(Nullable<int> userId, Nullable<int> storyId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var storyIdParameter = storyId.HasValue ?
                new ObjectParameter("StoryId", storyId) :
                new ObjectParameter("StoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStoryView", userIdParameter, storyIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CheckIfViewed(Nullable<int> storyId, Nullable<int> userId)
        {
            var storyIdParameter = storyId.HasValue ?
                new ObjectParameter("StoryId", storyId) :
                new ObjectParameter("StoryId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CheckIfViewed", storyIdParameter, userIdParameter);
        }
    
        public virtual int DeletePostById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePostById", idParameter);
        }
    
        public virtual int addarchievepost(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addarchievepost", idParameter);
        }
    
        public virtual int removearchievepost(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("removearchievepost", idParameter);
        }
    }
}
