//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public int MessageId { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> MessageTime { get; set; }
    
        public virtual UserData UserData { get; set; }
        public virtual UserData UserData1 { get; set; }
    }
}
